version: '2'
services:
  scrapyd:
    build:
      args:
        - USER_BASIC_AUTH=$USER_BASIC_AUTH
        - ADMIN_BASIC_AUTH=$ADMIN_BASIC_AUTH
      context: .
      dockerfile: Dockerfile
    ports:
      - '6800:6800'
    expose:
      - 6800
    volumes:
      - scrapyd-data:/var/lib/scrapyd
volumes:
  scrapyd-data:
